name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Determine branch deploy URL
      id: branch-url
      run: echo "BRANCH_URL=https://${{ github.head_ref || github.ref_name }}--pedigreesync.netlify.app/" >> $GITHUB_ENV
    - name: Run Playwright Tests
      env:
        BRANCH_URL: ${{ env.BRANCH_URL }}
      run: |
        npx playwright test --url $BRANCH_URL
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
